### ISSUE TITLE
Lack of license & copyright notices

### ISSUE THREAD

**Issue by rouault** [r-barnes/richdem#1]
I couldn't find any mention of the license of the code.

**Comment by r-barnes** [comment]
Thanks for reminding me of this. I'm endeavouring to figure out what the best license would be!

Are there any licensing restrictions for your use case?

**Comment by col16** [comment]
Hi Richard. I've just come across this repository via your (excellent) 2014 paper on Priority Flood. It's fantastic to have code available, particularly the parallel implementations. I'd like to echo Evan's request for a formal license. I can certainly appreciate the sentiment of "this value is yours to use", referring to the time you've put into it! But that statement wouldn't have much legal weight, and doesn't protect you from liability.

I'd love to see your software integrated into commercial GIS packages that do watershed delineation, such as ArcHydro and Global Mapper. I'm also toying with the idea of using it for a project that could earn a bit of income (a service aimed at providing hydrology data for remote areas). So my request would be for a permissive license such as MIT or BSD.

**Comment by r-barnes** [comment]
@col16: Thanks for commenting on this. I've been struggling with this back and forth for a while now.

From an academic/FOSS perspective, I want to see this code out there and used to make the world better.

From a "living on rice and beans" as an early-career academic perspective, there's one particular company (*cough* ESRI) that profits from a widely-used closed-source codebase with some seriously out-dated algorithms. In an ideal world, I would find a way to profitably consult with them to update said algorithms in way that's compatible with their data structures and, concomitantly, release this code into the wild with a permissive license. Figuring out how feasible that is has been a hang-up on licensing this.

Maybe there is no chance of this, and I should license the code permissively. Maybe licensing the code would have no impact, in which case it is foolish to wait. I don't know.

In anticipation of releasing this code into the wild, I am working on wrappers which will make it easily accessible from within both R and Python.

If you need some sort of personal license in the meantime, send me an email. All thoughts are welcome.

**Comment by rouault** [comment]
My 2 cents (and I'm not a lawyer): As currently done, nobody can legally use and distribute your code. What you could possibly do is release it under GPL v2+, AGPL or similar copyleft licenses, make sure that all future potential (and past) contributors other than you assign their copyright to you (contributor license agreement), or don't accept any external contribution, and then one day if you want to re-license it to a more liberal license (or sell proprietary licenses), you are free to do so.

**Comment by r-barnes** [comment]
@rouault: I'm working on putting together a Python wrapper for the library and thinking about the GPLv2+; I expect to finalize licensing sometime in the next couple of weeks. Does GPLv2+ work for your purposes?

I wonder why you were looking into this?

**Comment by rouault** [comment]
> I wonder why you were looking into this?

I can't remember why I went to your project ;-) I don't have a personal need for it right now, so feel free to pick up what is best for you.

**Comment by r-barnes** [comment]
The project is now licensed GPLv3.

It's on my TODO list to put license headers on the code.
