### ISSUE TITLE
Unable to build for windows

### ISSUE THREAD

**Issue by Froglich** [r-barnes/richdem#2]
I am trying to build RichDEM for Windows on an Arch Linux box. I have installed MinGW and am running make as 

$ make -f makefile.win

But the makefile expects me to have a dir named "richdem_windows", which does not exist so the build fails.

    $ make -f makefile.win 

    i686-w64-mingw32-g++ `../../richdem_windows/install/bin/gdal-config --cflags` --std=c++11 -o rd_flood_for_flowdirs.exe flood_for_flowdirs.cpp `../../richdem_windows/install/bin/gdal-config --libs` `../../richdem_windows/install/bin/gdal-config --dep-libs` -static-libgcc -static-libstdc++

    /bin/sh: ../../richdem_windows/install/bin/gdal-config: No such file or directory

    /bin/sh: ../../richdem_windows/install/bin/gdal-config: No such file or directory

    /bin/sh: ../../richdem_windows/install/bin/gdal-config: No such file or directory

    In file included from richdem/depressions/priority_flood.hpp:9:0,
                 from flood_for_flowdirs.cpp:5:

    richdem/depressions/../common/Array2D.hpp:10:23: fatal error: gdal_priv.h: No such file or directory
 
    #include "gdal_priv.h"
                       ^

    
    
    compilation terminated.

    make: *** [makefile.vars:18: flood_for_flowdirs] Error 1

**Comment by r-barnes** [comment]
The `richdem_windows` directory was part of an effort to build a statically-linked version of the GDAL library for building Windows binaries.

I've now abandoned this effort in favour of distributing the code via Python, which, hopefully, will make the GDAL dependency easier to work with.

You can now install and use many of RichDEM's tools using:

    pip3 install richdem
