### ISSUE TITLE
Setting geotransform for rdarray

### ISSUE THREAD

**Issue by DavidLitwin** [r-barnes/richdem#20]
I'm trying to set the geotransform on an rdarray that I make from a numpy array. It doesn't seem to be working, as that attribute of the rdarray remains blank after I set it, and "Warning! No geotransform defined...." continues to appear after I run FillDepressions and FlowAccumulation. Can anyone help?

`eta = np.ones((len(x),len(y)))*z_0 + 0.01*np.random.rand(len(x),len(y))
 dem = rd.rdarray(eta, no_data=-9999, geotransform = (0.0,delta,0.0,0.0,0.0,delta))
 rd.FillDepressions(dem, epsilon=False, in_place=True)`

**Comment by giswqs** [comment]
You probably need to define a projection. See an example below:

```
# get rdarray metadata
def getMetadata(img):
    no_data = img.no_data
    projection = img.projection
    geotransform = img.geotransform
    cell_size = np.round(geotransform[1], decimals=2)
    return no_data, projection, geotransform, cell_size

# convert numpy array to rdarray
def np2rdarray(in_array, no_data, projection, geotransform):
    out_array = rd.rdarray(in_array, no_data=no_data)
    out_array.projection = projection
    out_array.geotransform = geotransform
    return out_array

# main script
image = rd.LoadGDAL('path/to/tif')
no_data, projection, geotransform, resolution = getMetadata(image)
np_array = 'do some with np array'
out_image = np2rdarray(np_array, no_data, projection, geotransform)
rd.SaveGDAL('path/to/output/image', out_image)
```

**Comment by DavidLitwin** [comment]
Thank you, defining the projection solved the problem.
