### ISSUE TITLE
parallel_priority_flood: processes are occupied

### ISSUE THREAD

**Issue by xuezhicang** [r-barnes/richdem#27]
Since my data volume is very large, I am trying to use the parallel_priority_flood tool (https://github.com/r-barnes/richdem/tree/master/programs/parallel_priority_flood) to fill the pits.

I have compiled the program. When I run the program, it reported error message as below:
****************************************************
Job starting at: Sun Jun 23 23:12:09 CDT 2019
****************************************************
c Program name       = RichDEM v2.2.9
c Script compiled at = 2019-06-23 17:13:10 UTC
c Git hash           = abc04d81216d7cf5
c Copyright          = Richard Barnes © 2018
a Analysis command   = ./parallel_pf.exe one @offloadall ./dem_srtm_18_04/srtm_18_04.tif outroot -w 500 -h 500
A Barnes (2016) Parallel Priority-Flood
C Barnes, R., 2016. Parallel priority-flood depression filling for trillion cell digital elevation models on desktops or clusters. Computers & Geosciences 96, 56-68. doi:10.1016/j.cageo.2016.07.001
parallel_pflood.exe [--flipV] [--flipH] [--bwidth #] [--bheight #] <many/one> <retention> <input> <output>
        Use '--help' to show help.
E Retention must be @evict or @retain or a path.
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[30101,1],0]
  Exit code:    255
--------------------------------------------------------------------------
****************************************************
Job completed at: Sun Jun 23 23:12:12 CDT 2019
****************************************************

Would you please help me troubleshoot it?
Thank you for your help and time in advance. @r-barnes

**Comment by r-barnes** [comment]
`@offloadall` is not a valid option. Choose `@evict` or `@retain`, as suggested by the error message and the help text.

**Comment by xuezhicang** [comment]
Thanks! The program works.
