### ISSUE TITLE
segmentation fault in parallel_pf.exe

### ISSUE THREAD

**Issue by theobarnhart-USGS** [r-barnes/richdem#3]
Hi Rich,

I'm trying to get parallel_pf to run on my local machine and also on a USGS cluster and I get a segmentation fault in both when it runs (error below). It compiled without issue. Am I calling it correctly? I just want to do some simple comparisons with other algorithms.

Thank you!

(richDEM) tbarnhart@parallel_priority_flood$ mpirun -n 2 ./parallel_pf.exe one @
evict ~/projects/DEM_processing/data/test_data.tiff %n_richDEM_fill.tiff
c Program name       = RichDEM v0.0.0
c Script compiled at = 2018-01-02 20:34:19 UTC
c Git hash           = f138566c85cb70b7
c Copyright          = Richard Barnes © 2016
a Analysis command   = ./parallel_pf.exe one @evict /home/tbarnhart/projects/DEM
_processing/data/test_data.tiff %n_richDEM_fill.tiff
A A Barnes (2016) Parallel Priority-Flood
C C Barnes, R., 2016. "Parallel priority-flood depression filling for trillion c
ell digital elevation models on desktops or clusters". Computers & Geosciences.
doi:10.1016/j.cageo.2016.07.001
c Running with = 2 processes
c Many or one = one
c Input file = /home/tbarnhart/projects/DEM_processing/data/test_data.tiff
c Retention strategy = @evict
c Block width = -1
c Block height = -1
c Flip horizontal = 0
c Flip vertical = 0
c World Size = 2
m Total width =  2401
m Total height = 3601
m Block width =  2401
m Block height = 3601
m Total cells to be processed = 8646001
t Preparer time = 0.009007 s
[IGSKKBCWLT762:08182] *** Process received signal ***
[IGSKKBCWLT762:08182] Signal: Segmentation fault (11)

**Comment by r-barnes** [comment]
Sorry about that, some output info used for tiled datasets was mistakenly being displayed by the single tile mode resulting in the segfault: a one-line fix :-/

Things should be working as of v2.0.2

**Comment by r-barnes** [comment]
The Python command line tools should be available now for easy serial execution as well: I'll be sending around an email about that in the next day or two.

**Comment by theobarnhart-USGS** [comment]
Thank you Rich! That did the trick.
