### ISSUE TITLE
Documentation link in README not working

### ISSUE THREAD

**Issue by johnniehard** [r-barnes/richdem#32]
Hi @r-barnes,

just wanted to let you know the documentation link in the README is not working. I get this when clicking the link:

![image](https://user-images.githubusercontent.com/9264787/66462622-c47e4f80-ea7b-11e9-8d30-be1e1c592869.png)

**Comment by r-barnes** [comment]
Thanks! I've updated a DNS record which should propagate in at most a day. The documentation is at "https://richdem.readthedocs.io/en/latest/" in the meantime.
