### ISSUE TITLE
Develop install error: Missing `lib/richdem/common/random.cpp`

### ISSUE THREAD

**Issue by feefladder** [r-barnes/richdem#47]
First of all, thanks for the great library! I wanted to delineate a catchment, for which there is a C++ function in methods, which is not exposed. So when trying to install, I got the above error. I could also not find any `.cpp` files in the `pyrichdem/libs` folder, so I don;t really understand why the setup.py points to files there.

# steps to reproduce

```
git clone git@github.com/r-barnes/richdem.git
cd richdem
conda create -n richdem-dev pip numpy
conda activate richdem-dev
pip install -e wrappers/pyrichdem
```
gives the error that setup.py looks for `random.cpp` and `richdem.cpp` [here](https://github.com/r-barnes/richdem/blob/603cd9d16164393e49ba8e37322fe82653ed5046/wrappers/pyrichdem/setup.py#L50).

Now, if I remove those  by commenting them out, compilation works (it actually takes quite some time, but I get a NOTHING WILL WORK! error when I 
`import richdem`. Then, if I `import _richdem`, I get the following obscure error:
``` 
ImportError: /miniconda3/envs/richdem-dev/lib/python3.10/site-packages/_richdem.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN7richdem9RDLOGfuncENS_7LogFlagEPKcS2_jNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
# proposed solution
Documentation on how to buidl the python part of RichDem if that's not too difficult?

**Comment by cuill** [comment]
You have to cd into wrappers/pyrichdem directory to do "pip install -e . ", then you will have the correct path to "random.cpp" and "richdem.cpp":
 glob.glob('src/*.cpp') + ['lib/richdem/common/random.cpp', 'lib/richdem/richdem.cpp']

**Comment by feefladder** [comment]
big oops, my fork was horribly behind (47 commits) and it was solved in the meantime.... closing now.
