### ISSUE TITLE
BreachDepressions missing in python RichDEM

### ISSUE THREAD

**Issue by theobarnhart-USGS** [r-barnes/richdem#6]
Hi Rich,

I'm back to testing out some of these tools in python. RichDEM installed to a python 3 environment without a hitch on one of the USGS clusters! However, it seems that the BreachDepressions function is missing although it is documented at richdem.com. Here is the error I get:

```
In [12]: rd.BreachDepressions(dat,mode='Complete',in_place=True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-ddda26957d72> in <module>()
----> 1 rd.BreachDepressions(dat,mode='Complete',in_place=True)

AttributeError: module 'richdem' has no attribute 'BreachDepressions'
```

I used `pip install richdem` to install the package.

Am I missing something about where the function went? I do not see in listed as a function when I use the `help(richdem)` command either. 

Thank you for all your work with this!

**Comment by r-barnes** [comment]
Sorry, I've just now seen this.

Depression breaching is now included (see [this](https://richdem.readthedocs.io/en/latest/depression_breaching.html)).

It had been present until I found a bug in the selective breaching algorithm. I haven't yet fixed down the cause of that, so I've released only complete breaching for now.
